### PR TITLE
JDK download update + Open project with last used window mode + SublimeText download update

### PR DESCRIPTION
**Pull request by AndrewEQ**
- SublimeText download update: https://forums.fusetools.com/t/unable-to-install-sublime-fuse-plugin/7520/3
Requires PR approval at the plugin first: https://github.com/fuse-open/Fuse.SublimePlugin/pull/35

- Updated JDK download urls to download direct from Oracle and added cookie support to allow download via acceptance cookie
- Updated initial window mode to open project with the last used window mode

This PR includes:
- [ ] Change log
- [ ] Tests

### CODE REVIEW

**Comment by mortend** [comment]
Thank you!

I ended up creating a GitHub release for sublime plugin, and this changes the download URL to https://github.com/fuse-open/Fuse.SublimePlugin/releases/download/1.5.0/FuseSublimePlugin_1_5_0.zip

Can you please update your last commit with the new URL?

---

PS: In the future, it will be helpful to receive separate PRs for different unrelated changes. Three separate PRs instead of a 3-in-1-PR is easier to manage, and now you're kind of forcing me to take all or nothing. If it turns out to be a problem with one of the features, it becomes more difficult to revert only the problematic feature, and things like that. :)

**Comment by AndrewEQ** [comment]
Thanks man, will do, yeah my bad, I forgot to make a separate branch+PR for each, gotta get into the habit.

**Comment by AndrewEQ** [comment]
Ok, just updated the download urls!

**Comment by mortend** [comment]
Cool, thanks!

Since the Travis CI build looks like a spurious failure in unrelated tests, which seems to happen often, and I don't have the power yet to trigger a rebuild - I think I'll just go ahead and merge this, and soon start preparing the release branch...

**Pull request merged**
